# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/dev/HackEdit/hackedit/data/forms/settings_page_templates.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(810, 519)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_git_not_found = QtWidgets.QLabel(Form)
        self.lbl_git_not_found.setStyleSheet("background-color: #DD8080;\n"
"color: white;\n"
"padding: 10px;\n"
"border-radius:3px;")
        self.lbl_git_not_found.setObjectName("lbl_git_not_found")
        self.verticalLayout.addWidget(self.lbl_git_not_found)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_add_source = QtWidgets.QPushButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_add_source.setIcon(icon)
        self.bt_add_source.setObjectName("bt_add_source")
        self.horizontalLayout_2.addWidget(self.bt_add_source)
        self.bt_rm_source = QtWidgets.QPushButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_rm_source.setIcon(icon)
        self.bt_rm_source.setObjectName("bt_rm_source")
        self.horizontalLayout_2.addWidget(self.bt_rm_source)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.bt_sync = QtWidgets.QPushButton(self.groupBox_2)
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.bt_sync.setIcon(icon)
        self.bt_sync.setObjectName("bt_sync")
        self.horizontalLayout_2.addWidget(self.bt_sync)
        self.cb_auto_sync = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_auto_sync.setObjectName("cb_auto_sync")
        self.horizontalLayout_2.addWidget(self.cb_auto_sync)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.list_sources = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_sources.sizePolicy().hasHeightForWidth())
        self.list_sources.setSizePolicy(sizePolicy)
        self.list_sources.setObjectName("list_sources")
        self.horizontalLayout_3.addWidget(self.list_sources)
        self.group_details = QtWidgets.QGroupBox(self.groupBox_2)
        self.group_details.setObjectName("group_details")
        self.formLayout_2 = QtWidgets.QFormLayout(self.group_details)
        self.formLayout_2.setSpacing(12)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.group_details)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.group_details)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtWidgets.QLabel(self.group_details)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.group_details)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.group_details)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.list_templates = QtWidgets.QListWidget(self.group_details)
        self.list_templates.setObjectName("list_templates")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.list_templates)
        self.edit_source_label = QtWidgets.QLabel(self.group_details)
        self.edit_source_label.setText("")
        self.edit_source_label.setObjectName("edit_source_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_source_label)
        self.edit_source_path = QtWidgets.QLabel(self.group_details)
        self.edit_source_path.setText("")
        self.edit_source_path.setObjectName("edit_source_path")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_source_path)
        self.edit_sync_time = QtWidgets.QLabel(self.group_details)
        self.edit_sync_time.setText("")
        self.edit_sync_time.setObjectName("edit_sync_time")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_sync_time)
        self.edit_source_cache = QtWidgets.QLabel(self.group_details)
        self.edit_source_cache.setText("")
        self.edit_source_cache.setObjectName("edit_source_cache")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_source_cache)
        self.horizontalLayout_3.addWidget(self.group_details)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.lbl_boss_version = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_boss_version.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_boss_version.setOpenExternalLinks(True)
        self.lbl_boss_version.setObjectName("lbl_boss_version")
        self.verticalLayout_2.addWidget(self.lbl_boss_version)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        from hackedit.api.gettext import translation
        _ = translation(package="hackedit")
        Form.setWindowTitle(_("Form"))
        self.lbl_git_not_found.setText(_("<html><head/><body><p align=\"center\">Git not found in PATH, Sync will not work!</p></body></html>"))
        self.groupBox_2.setTitle(_("Sources"))
        self.bt_add_source.setToolTip(_("Add a template source repository"))
        self.bt_add_source.setText(_("Add"))
        self.bt_rm_source.setToolTip(_("Remove a source repository"))
        self.bt_rm_source.setText(_("Remove"))
        self.bt_sync.setToolTip(_("Sync source repositories (you need to have git in PATH)."))
        self.bt_sync.setText(_("Sync"))
        self.cb_auto_sync.setToolTip(_("Check this to automatically sync template repositories on application startup"))
        self.cb_auto_sync.setText(_("Sync on startup"))
        self.list_sources.setToolTip(_("The list of template source repositories"))
        self.group_details.setTitle(_("Details"))
        self.label.setText(_("Label:"))
        self.label_3.setText(_("Path:"))
        self.label_2.setText(_("Cache:"))
        self.label_4.setText(_("Last sync time:"))
        self.label_5.setText(_("Available templates:"))
        self.list_templates.setToolTip(_("The list of available templates provided by the selected source."))
        self.lbl_boss_version.setText(_("Powered by BOSS v0.9.20"))

